/*

 BKG_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 11

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bkg_spritesBank 0

/* Super Gameboy palette 0 */
#define bkg_spritesSGBPal0c0 6076
#define bkg_spritesSGBPal0c1 8935
#define bkg_spritesSGBPal0c2 6596
#define bkg_spritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bkg_spritesSGBPal1c0 6076
#define bkg_spritesSGBPal1c1 8935
#define bkg_spritesSGBPal1c2 6596
#define bkg_spritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bkg_spritesSGBPal2c0 6076
#define bkg_spritesSGBPal2c1 8935
#define bkg_spritesSGBPal2c2 6596
#define bkg_spritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bkg_spritesSGBPal3c0 6076
#define bkg_spritesSGBPal3c1 8935
#define bkg_spritesSGBPal3c2 6596
#define bkg_spritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bkg_spritesCGBPal0c0 32767
#define bkg_spritesCGBPal0c1 8935
#define bkg_spritesCGBPal0c2 6596
#define bkg_spritesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define bkg_spritesCGBPal1c0 32767
#define bkg_spritesCGBPal1c1 503
#define bkg_spritesCGBPal1c2 337
#define bkg_spritesCGBPal1c3 106

/* Gameboy Color palette 2 */
#define bkg_spritesCGBPal2c0 32767
#define bkg_spritesCGBPal2c1 26425
#define bkg_spritesCGBPal2c2 15855
#define bkg_spritesCGBPal2c3 5120

/* Gameboy Color palette 3 */
#define bkg_spritesCGBPal3c0 32767
#define bkg_spritesCGBPal3c1 7167
#define bkg_spritesCGBPal3c2 6047
#define bkg_spritesCGBPal3c3 479

/* Gameboy Color palette 4 */
#define bkg_spritesCGBPal4c0 6076
#define bkg_spritesCGBPal4c1 8935
#define bkg_spritesCGBPal4c2 6596
#define bkg_spritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define bkg_spritesCGBPal5c0 6076
#define bkg_spritesCGBPal5c1 8935
#define bkg_spritesCGBPal5c2 6596
#define bkg_spritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bkg_spritesCGBPal6c0 6076
#define bkg_spritesCGBPal6c1 8935
#define bkg_spritesCGBPal6c2 6596
#define bkg_spritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bkg_spritesCGBPal7c0 6076
#define bkg_spritesCGBPal7c1 8935
#define bkg_spritesCGBPal7c2 6596
#define bkg_spritesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char bkg_spritesCGB[];
/* Start of tile array. */
extern unsigned char bkg_sprites[];

/* End of BKG_SPRITES.H */
