/*

 BKGSPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bkgSpritesBank 0

/* Super Gameboy palette 0 */
#define bkgSpritesSGBPal0c0 6076
#define bkgSpritesSGBPal0c1 8935
#define bkgSpritesSGBPal0c2 6596
#define bkgSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bkgSpritesSGBPal1c0 6076
#define bkgSpritesSGBPal1c1 8935
#define bkgSpritesSGBPal1c2 6596
#define bkgSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bkgSpritesSGBPal2c0 6076
#define bkgSpritesSGBPal2c1 8935
#define bkgSpritesSGBPal2c2 6596
#define bkgSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bkgSpritesSGBPal3c0 6076
#define bkgSpritesSGBPal3c1 8935
#define bkgSpritesSGBPal3c2 6596
#define bkgSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bkgSpritesCGBPal0c0 32767
#define bkgSpritesCGBPal0c1 6879
#define bkgSpritesCGBPal0c2 573
#define bkgSpritesCGBPal0c3 3551

/* Gameboy Color palette 1 */
#define bkgSpritesCGBPal1c0 6076
#define bkgSpritesCGBPal1c1 8935
#define bkgSpritesCGBPal1c2 6596
#define bkgSpritesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define bkgSpritesCGBPal2c0 6076
#define bkgSpritesCGBPal2c1 8935
#define bkgSpritesCGBPal2c2 6596
#define bkgSpritesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define bkgSpritesCGBPal3c0 6076
#define bkgSpritesCGBPal3c1 8935
#define bkgSpritesCGBPal3c2 6596
#define bkgSpritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define bkgSpritesCGBPal4c0 6076
#define bkgSpritesCGBPal4c1 8935
#define bkgSpritesCGBPal4c2 6596
#define bkgSpritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define bkgSpritesCGBPal5c0 6076
#define bkgSpritesCGBPal5c1 8935
#define bkgSpritesCGBPal5c2 6596
#define bkgSpritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bkgSpritesCGBPal6c0 6076
#define bkgSpritesCGBPal6c1 8935
#define bkgSpritesCGBPal6c2 6596
#define bkgSpritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bkgSpritesCGBPal7c0 6076
#define bkgSpritesCGBPal7c1 8935
#define bkgSpritesCGBPal7c2 6596
#define bkgSpritesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char bkgSpritesCGB[];
/* Start of tile array. */
extern unsigned char bkgSprites[];

/* End of BKGSPRITES.H */
